### ISSUE TITLE
Add GitHub stats and visitor count in your readme

### ISSUE THREAD

**Issue by sanchitvj** [gvinayakgupta/gvinayakgupta#1]
For stats use this code:
(give your username in the place of id)
`![](https://github-readme-stats.vercel.app/api?username=id&show_icons=true&title_color=E88795&icon_color=FF33FF&text_color=D6BCD5&bg_color=151515)`
It will look something like this:
![](https://github-readme-stats.vercel.app/api?username=sanchitvj&show_icons=true&title_color=E88795&icon_color=FF33FF&text_color=D6BCD5&bg_color=151515)
  
For visitor count:
`![VisitorCount](https://profile-counter.glitch.me/{id}/count.svg)
`
![VisitorCount](https://profile-counter.glitch.me/{sanchitvj}/count.svg) 

Star the [repo](https://github.com/sanchitvj/sanchitvj) if you like it.

**Comment by vinayakguptaa** [comment]
Thanks for the suggestions...
